### PR TITLE
Update developer guide for Origin Trial v0.2

### PR DESCRIPTION
**Pull request by stephenmcgruer**
This PR expands the guide to include:

- A quick description of SPC.
- An explanation of what Origin Trial v0.2 is for.
- A few more details on enrolling for the Origin Trial.
- Two more questions in the FAQ.

(Includes some text originally written by Danyao)

-----

[Rendered view](https://github.com/w3c/secure-payment-confirmation/blob/50379a17e8c8984d730c12273e6d342b3a0c11a7/developer-guide.md) of the PR.

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]
Looks good from technical standpoint. Thank you! (I did not review English grammar or punctuation.)

**Review by ianbjacobs — APPROVED** [review]

**Review by nickburris — APPROVED** [review]
LGTM!

**Comment by ianbjacobs** [comment]
Hi all,

Thanks for reviewing Stephen's request. I have reported to the systems team that the IPR check seems to be failing; stay tuned.

Ian

**Comment by dontcallmedom** [comment]
I've marked the PR as non-substantive since it doesn't touch normative content. @stephenmcgruer if you want your PR automatically accepted, you'll need to bind your github & W3c accounts through https://www.w3.org/users/myprofile/connectedaccounts

**Comment by stephenmcgruer** [comment]
> I've marked the PR as non-substantive since it doesn't touch normative content. @stephenmcgruer if you want your PR automatically accepted, you'll need to bind your github & W3c accounts through https://www.w3.org/users/myprofile/connectedaccounts

Done. It was strange to me that this was needed though - [this PR](https://github.com/w3c/secure-payment-confirmation/pull/58) 8 days ago was fine, and historically I've contributed to W3C ... *shrug*.

**Pull request merged**
