### PR TITLE
Note about credential reuse in both directions

### PR DESCRIPTION
**Pull request by ianbjacobs**
This pull request comes from an issue raised by @Goosth [1] and discussed at today's SPC task force call.

[1] https://github.com/w3c/secure-payment-confirmation/pull/103

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/104.html" title="Last updated on Aug 20, 2021, 2:53 PM UTC (4c5e898)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/104/44ef82b...4c5e898.html" title="Last updated on Aug 20, 2021, 2:53 PM UTC (4c5e898)">Diff</a>

### CODE REVIEW

**Review by stephenmcgruer — APPROVED** [review]
This is fine by me, but I'll leave it up to @Goosth as to how he wanted this phrased.

**Comment by ianbjacobs** [comment]
@goosth, does this address the point you raised in your general review?

**Comment by Goosth** [comment]
@ianbjacobs, not sure this is accurate. My expectation is that these WebAuthn credentials will be usable for Login as well as payments.

My attempt at it

     Although SPC depends on the extension, it does not preclude the 
     WebAuthn credentials from being used in other use-cases (e.g. Login).
     So these credentials are are fully fledged WebAuthn Credentials and 
     not limited to SPC usage in any way.

If you want to add:
     Also note that their usage may change as WebAuthn's usage of 
     extensions evolve outside of this specification.

**Comment by ianbjacobs** [comment]
@Goosth, I've made edits based on your comments. Thanks!

**Pull request merged**
