### PR TITLE
[Spec] Do not use WebIDL to define WebDriver parameters

### LINKED ISSUE #219: Use lowercase values in enum
#215 introduced enum values that use camel-case; the convention for Web specs is to use [lowercase, dash-separated values for enums](https://w3ctag.github.io/design-principles/#casing-rules)

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes #219

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/pull/221.html" title="Last updated on Jan 6, 2023, 3:04 PM UTC (a7edd49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/secure-payment-confirmation/221/c24f564...a7edd49.html" title="Last updated on Jan 6, 2023, 3:04 PM UTC (a7edd49)">Diff</a>

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
cc @foolip and @dontcallmedom as an fyi - feel free to let me know if the change isn't what you were expecting :)

**Review by ianbjacobs — APPROVED** [review]

**Comment by ianbjacobs** [comment]
I trust you on this one!

**Comment by stephenmcgruer** [comment]
@rsolomakhin - ping for review too, thanks :)

**Comment by rsolomakhin** [comment]
LGTM! Sorry about the delay.

**Review by rsolomakhin — APPROVED** [review]

**Pull request merged**
