### PR TITLE
[Spec] Add payeeOrigin

### PR DESCRIPTION
**Pull request by stephenmcgruer**
Fixes https://github.com/w3c/secure-payment-confirmation/issues/83

### CODE REVIEW

**Comment by stephenmcgruer** [comment]
I'm curious on folks' thoughts on whether to make this field required, or whether to auto-compute it if empty (to `topOrigin`), or to leave it empty if not set.

Given the UX is likely showing it, I think we have to either do required or auto-computed.

**Comment by rsolomakhin** [comment]
Requiring the field should make the algorithms simpler without putting too much burden on the web developers. That's my personal preference, but I'm happy to hear other opinions.

**Comment by ianbjacobs** [comment]
@jcemer, @apouillard, @a-akimov, @mweksler, @bdewater, @Goosth, any thoughts on this?
Ian

**Comment by Goosth** [comment]
We need to consider the different form-factors. E.g. what if the merchant does not support SPC, but the Issuer/Account Provider does, and wants to use it in the Account Provider context. At first glance I would say
* It makes sense to support some form of topOrigin/callingparty field
* Should be auto-filled by the browser
* Should be included in signature.

**Comment by apouillard** [comment]
I'd rather make this merchantOrigin a required field. However, as the payee is not always a merchant, maybe should we think about a more generic name for this field...

**Comment by SensibleWood** [comment]
> I'd rather make this merchantOrigin a required field. However, as the payee is not always a merchant, maybe should we think about a more generic name for this field...

+1 - it could be a PISP, for example

**Comment by stephenmcgruer** [comment]
Renaming is fine to me. `payeeOrigin`? `onBehalfOf`?

There are probably two concepts to keep in mind while we think about this:

1. What is shown in the auth-time UX, both for regulatory reasons and for user understanding.
  * This sub-divides into what a UA may want to show, and what a UA has to show (for regulatory reasons). 
2. What concept ends up signed in the cryptogram.

**Comment by rsolomakhin** [comment]
> What concept ends up signed in the cryptogram.

The `payeeOrigin` proposal sounds good.

**Comment by stephenmcgruer** [comment]
PR updated to use `payeeOrigin`, and to make it `required` in SPC auth.

**Review by ianbjacobs — APPROVED** [review]

**Review by rsolomakhin — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
